title: Nicolas Brandão
description: Documentação técnica e tutoriais de infraestrutura de redes e nuvem.
remote_theme: just-the-docs/just-the-docs

# Configurações do Site
color_scheme: light 


aux_links:
  "LinkedIn": "https://www.inkedin.com/in/nícolas-brandão-b6471a237"
  "GitHub": "https://github.com/nicolasbrandaoc"

search_enabled: true
